name: Pylint

on:
  push:
    branches:
      - main
    schedule:
      - cron: "* 8 * * *"
        displayName: "Build daily at 8 a.m."
        branches:
          include:
            - main
        always: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest

      - name: Automated Testing
        run: |
          cd LF8/src
          pytest testAlarmsystem.py

